### ISSUE TITLE
Port NR functionality to LabVIEW

### ISSUE THREAD

**Issue by mdwhitten** [NISystemsEngineering/rfic-reference-design-libraries-labview#10]
This feature is to port the existing [NR implementation in C#](https://github.com/NISystemsEngineering/rfic-reference-design-libraries-csharp/tree/master/Source/SA/RFmx%20NR) to LabVIEW.

**Comment by mdwhitten** [comment]
@heyItsDale Any interest/bandwidth to tackle this development effort?

**Comment by heyItsDale** [comment]
Yeah that should be alright.
