### ISSUE TITLE
SG: Abort Generation.vi missing wait statement in polling loop

### ISSUE THREAD

**Issue by mdwhitten** [NISystemsEngineering/rfic-reference-design-libraries-labview#41]
Current code, below, is missing a Wait VI to properly match the C# implementation. This is causing error 5000 to be thrown regularly. Issue reported by @manderseck 
![image](https://user-images.githubusercontent.com/47825680/66763325-45b75700-ee6d-11e9-94f9-29d15df013cb.png)

```C#
            if (genStatus == RfsgGenerationStatus.InProgress)
            {
                for (int i = 0; i < maxIterations; i++)
                {
                    genStatus = rfsgHandle.CheckGenerationStatus();
                    if (genStatus == RfsgGenerationStatus.Complete)
                        break;
                    else
                        Thread.Sleep(sleepTime_ms);
                }
```

**Comment by manderseck** [comment]
A fix for this is included in commit 6d0e60ecdf68e18c9a98af4ef9d7952eac137cc9 which can be integrated via pull request #49
