### ISSUE TITLE
CFR enable in DPD should be removed

### ISSUE THREAD

**Issue by manderseck** [NISystemsEngineering/rfic-reference-design-libraries-labview#45]
We had a discussion with Dale about this: Currently you can enable and disable the pre-DPD CFR and post-DPD CFR but the RDLs don't offer any means to configure the CFR. Therefore we should leave away the whole CFR toggles.

**Comment by manderseck** [comment]
According to the Teams discussion the CFR toggles will stay and the CFR configuration will be added.

**Comment by cindyxie** [comment]
Changes are applied in commit https://github.com/NISystemsEngineering/rfic-reference-design-libraries-labview/commit/255b959ae9c1935177754a584cd948008d2f743a
