### ISSUE TITLE
Cosmetic/logical issues in DPD RDLs

### ISSUE THREAD

**Issue by manderseck** [NISystemsEngineering/rfic-reference-design-libraries-labview#46]
1. In Configure Common.vi the waveform cluster is not typedefed while in Perform Memory Polynomial.vi it is. Leads to coercion dot in the example.
2. In Configure Common.vi the Common Configuration Cluster has a line break at the end of its label. It's not visible in the RDL but if you create a control.
3. There's a setting "Iterative DPD enabled" which must be set to true if more than one iteration should be performed. While this seems to be an optimization of RFmx we could keep this setting under the hood and only expose the number of iterations and switch the "Iterative DPD enabled" automatically.

**Comment by cindyxie** [comment]
Changes are applied to commit https://github.com/NISystemsEngineering/rfic-reference-design-libraries-labview/commit/70b4afd5395482f2ee90dfeb26c03c0fede8a872
