### ISSUE TITLE
Perform Memory Polynomial.vi in DPD RDLs won't work

### ISSUE THREAD

**Issue by manderseck** [NISystemsEngineering/rfic-reference-design-libraries-labview#47]
The Memory Polynomial Results cluster that is fed with the output of the Apply Digital Predistortion.vi mainly has default values from the cluster constant. However, this cluster is then passed to the Download Waveform.vi which then works on the default waveform name (instead of the previously uesd one) and which doesn't have bandwidth, burst length or runtime scaling information to set them correctly to the SG. 
In order to apply the changed values correctly to the SG a Set Script to Generate.vi is missing. That might be omitted, too, if the waveform name doesn't change, however I have experienced different results in the AM/AM plot when doing this compared to setting the script to generate again.

**Comment by mkrmasch** [comment]
According to my understanding the set script is necessary to apply the playback library settings down to SG driver. I think it is mandatory.

**Comment by cindyxie** [comment]
Modified Perform Memory Polynomial.vi to pass the waveform parameters to memory polynomial results cluster. Changes are applied to commit https://github.com/NISystemsEngineering/rfic-reference-design-libraries-labview/commit/88000299dccf81e71159bcfdfe114fff1b07c476

**Comment by manderseck** [comment]
Fixed the Set Script to Generate with commit fdccf2a9
