### ISSUE TITLE
Recursive call in case of error into Configure Continuous Generation

### ISSUE THREAD

**Issue by manderseck** [NISystemsEngineering/rfic-reference-design-libraries-labview#61]
Take one of the RFIC examples, don't set the correct device identifiers, execute the example. The example will become unresponsive for quite a while, then a dialog states: "There are too many nested VI calls. This typically results from recursion without a proper termination condition to stop the recursion".
The reason is that Configure Continuous Generation.vi calls into Apply Waveform Attributes.vi which if the Script is empty again calls into Configure Continuous Generation. And because there's an error on the error wire it won't populate the script variable. It might be possible that this recursion will happen with other types of errors happening early in the code. We need to handle this better, I think, so that the original error can make it to the error out of the example.

**Comment by mdwhitten** [comment]
**Root cause:** `Format Into String` fails to output any string on incoming error string.
**Fix:** Remove error wires connecting to `Format Into String`. Add unit tests to check behavior.
