### ISSUE TITLE
Wrong enum type used in SpecAn + NR

### ISSUE THREAD

**Issue by smooresni** [NISystemsEngineering/rfic-reference-design-libraries-labview#66]
An enum from another personality (I think LTE) has made it into the measurement configuration functions for NR and SpecAn. While I don't expect it to cause problems immediately, we should be conscious that the enum values for measurement across personalities might be different.

**Comment by mdwhitten** [comment]
The only thing that I have found is that NR used `RFmxLTE Build Offset String`. I found this by opening an empty project and adding a single library, and checking the dependencies. Hence, I don't see any crossover enums that you are referring to. Could you help point me to what you are seeing? Or perform the same experiment?

**Comment by smooresni** [comment]
![image](https://user-images.githubusercontent.com/51342134/68975480-3860f580-07a8-11ea-9dc2-a303f04a1b8a.png)

There is a coercion dot.

**Comment by smooresni** [comment]
I have a coercion dot in mine.

![image](https://user-images.githubusercontent.com/51342134/68975526-5b8ba500-07a8-11ea-9d3c-f3cd55921487.png)

**Comment by mdwhitten** [comment]
Maybe it's a driver issue. I don't have any coercion dots in the entire library (used VI Analyzer to verify). The specific ones you showed don't include a coercion dot.

What version are you using? I have 19.1.

**Comment by smooresni** [comment]
that must be it. i have 19.0 on my machine.
