### ISSUE TITLE
Measurement/Trace Enabled Behavior for All Modules

### ISSUE THREAD

**Issue by mdwhitten** [NISystemsEngineering/rfic-reference-design-libraries-labview#9]
> ## ModAcc Config/Fetch & ACP Config/Fetch
> 1. Thus far, all measurement modules have intentionally enabled _All Traces_ even if not used because it makes the process easier for a user to modify the fetch later. As in, a new user might try to fetch a constellation trace from the ModAcc measurement and not know where to go to enable the trace when the error occurs. I recognize this is a hit to performance.
> 2. You have added a _Measurement Enabled_ parameter to each of the measurement configurations rather than enabling by default. That's an interesting addition; can you elaborate on your thinking? That may be a valuable addition for other modules as well but I want to understand your thinking first. The thinking thus far is that each configure should intentionally enable the measurement for ease-of-use, and a user would later use _Select Measurements_ in order to specifically select other measurements. Do you see an advantage to your method here?
> 
> With either of these changes I want to make a decision as to whether other modules need to be changed so that the interfaces are consistent across modules.

@mdwhitten 
1. Changed VIs to enable all traces by default
2. Encapsulation. Each configuration method is responsible for enabling or disabling the measurement. Nobody else is. Helps contain measurement configuration and properties to a single VI call for that measurement. I view Measurement Enabled as a property of the measurement itself.

_Originally posted by @smooresni in https://github.com/NISystemsEngineering/rfic-reference-design-libraries-labview/pull/3#issuecomment-516094188_

**Comment by mdwhitten** [comment]
@smooresni I am opening an issue here for us to discuss this further as it has an impact on all modules both for C# and LabVIEW. I think you have an interesting point here, but I am thinking that if we do this we should also place "Traces Enabled" as an input per each measurement (default true). My only concern is making the measurement configuration clusters/structs too involved with the addition of two more parameters. 

@cluton99 what are your thoughts? For reference, @smooresni added a **Measurement Enabled** property to RFmx configuration functions, which we just had as a default value before.

**Comment by cluton99** [comment]
@mdwhitten @smooresni I understand that enabling all by default results in a performance hit. In general, when making a choice between ease of use and speed, the path for the RDLs has been ease of use. This was why we chose to enable all. I would prefer to keep that convention but could be persuaded otherwise

**Comment by mdwhitten** [comment]
@smooresni: @cluton99 and I discussed this further. The desired behavior that we are after is that each module configuration by default enables the measurement and its traces, such that a user can call `RFmx Initiate` without having to make any further calls. The upside of this is simplicity and ease, while the downsides of this assumption, of course, are performance. We are by default directing the user to run measurements and gather traces they may or may not be interested in.

We think it is the right approach to start with the simple case and allow the customer to further optimize if so desired, and hope to not insert significant barriers to that optimization. One approach is what you have adopted here. It is clear that adding this functionality would allow for greater flexibility without significantly over-complicating existing implementations. 

However, it does not seem to offer particular benefits over using `Select Measurements`, which would similarly allow the user more control over the process. Moreover, this function would also allow you to control `All Traces Enabled` properties with the measurements that are being selected. Hence, it seems in this case that the simplest solution would be to leave the measurement or trace enabled booleans out of the configuration, and let `Select Measurements` be our recommendation. 

**What are your thoughts? Can you think of any use cases where this offers particular value over `Select Measurements`?**

**Comment by smooresni** [comment]
@mdwhitten @cluton99 I have no rebuttal to not enabling all traces by default. Makes sense to me and the right move to make given Michael's reasoning. Agree that RDLs should assume all traces enabled and should not expose a boolean control for it in measurement configuration cluster.

I'll concede on the measurement enabled boolean. It just seemed like a simple way to expose greater control to the user without any added complexity. Also could potentially avoid a wrapper to SelectMeasurements in TestStand.

**Comment by smooresni** [comment]
@mdwhitten @cluton99 closing this issue since we've reached consensus.
